// app/lib/automations.ts
//
// Storage + lifecycle for user-defined Automations ("flows"): standing rules
// of the form "when <trigger>, do <action>". A trigger is a schedule, a
// Composio event (e.g. new Gmail), a generic inbound webhook, or a chat
// keyword. An action is either a lightweight durable step list (trivial
// pure-VFS / send ops) or a full durable agent job (see automationWorkflow).
//
// Redis layout (all under the `auto:` prefix, no TTL — these are standing
// rules and their run history, same persistence contract as nx_evals):
//
//   auto:rule:{id}                  JSON   Automation
//   auto:by_tenant:{t}              SET    automation ids
//   auto:by_trigger:{triggerType}   SET    automation ids (composio match)
//   auto:schedule                   ZSET   automation id -> nextAt (ms)
//   auto:run:{runId}                JSON   AutomationRun
//   auto:runs:by_rule:{id}          ZSET   run ids, newest first (-ts)
//   auto:runs:by_tenant:{t}         ZSET   run ids, newest first (-ts)
//
// fireAutomation() is the single entrypoint every trigger source funnels
// through; it records a run and launches the durable automationWorkflow.

import { getStore } from "@/app/lib/store";
import type { Channel } from "@/app/lib/identity";
import { env } from "@/app/lib/env";

// --- types --------------------------------------------------------------

export type AutomationTrigger =
  | {
      kind: "schedule";
      // Exactly one of cron / everyMs drives the cadence. nextAt is the next
      // fire time in epoch ms (maintained in the auto:schedule ZSET too).
      cron?: string; // standard 5-field: "min hour dom month dow"
      everyMs?: number; // simple fixed interval
      tz?: string; // IANA tz for cron wall-clock (default UTC)
      nextAt: number;
    }
  | {
      kind: "composio";
      triggerType: string; // e.g. GMAIL_NEW_GMAIL_MESSAGE
      filter?: Record<string, string>; // substring match against event payload
      triggerId?: string; // Composio subscription instance id, once registered
    }
  | {
      kind: "webhook";
      secret: string; // required in the inbound URL to fire
    }
  | {
      kind: "chat";
      pattern: string; // regex tested against inbound message text
      flags?: string; // regex flags (default "i")
    };

export type LightStep =
  | { op: "send"; text: string }
  | { op: "vfs_write"; path: string; content: string }
  | { op: "vfs_append"; path: string; content: string };

// A single parameter value inside a deterministic plan step. Resolved at run
// time, and this is the ONLY place a plan touches an LLM:
//   const — a fixed value baked in when the automation was compiled.
//   event — pulled from the triggering event payload by dot-path (e.g. the
//           incoming email's "subject" / "from").
//   ai    — generated by a single LLM call at run time (e.g. the body of an
//           email, a summary). Use this ONLY for genuinely generative inputs.
// Deterministic workflows are mostly const/event; ai is the exception, so a
// plan that just "send this fixed message every morning" spends zero tokens.
export type PlanValue =
  | { from: "const"; value: string }
  | { from: "event"; path: string }
  | { from: "ai"; prompt: string };

// One step of a deterministic plan. Unlike a job, the tool + its parameters are
// fixed at compile time — the runtime executes them directly (see
// runPlanStepsStep) without an agent deciding which tool to call or
// regenerating arguments on every fire.
export type PlanStep =
  | { op: "send"; text: PlanValue }
  | { op: "vfs_write"; path: string; content: PlanValue }
  | { op: "vfs_append"; path: string; content: PlanValue }
  | {
      op: "composio";
      tool: string; // Composio tool slug, e.g. GMAIL_SEND_EMAIL
      args: Record<string, PlanValue>;
      connectedAccountId?: string;
    };

export type AutomationAction =
  | { mode: "job"; instruction: string; deep: boolean; skills?: string[] }
  | { mode: "light"; steps: LightStep[] }
  // Deterministic tool-call workflow: a fixed ordered list of steps (send / VFS
  // / Composio tool calls) with parameters bound at compile time. Runs directly
  // via runPlanStepsStep, calling the LLM only for fields marked `ai`. This is
  // the durable-workflow path for the many automations whose behavior is fully
  // determined once compiled ("email me the weather at 8am", "append this row").
  | { mode: "plan"; steps: PlanStep[] }
  // Run a workforce (team of scoped sub-agents) — see app/lib/agents.ts and
  // app/workflows/workforceWorkflow.ts. The rule carries only the pointer;
  // stages/members live on the Workforce record.
  | { mode: "workforce"; workforceId: string };

export type AutomationStatus = "active" | "paused" | "error";

export type Automation = {
  id: string;
  tenantId: string;
  channel: Channel;
  sessionId: string;
  name: string;
  spec: string; // the raw natural-language description
  trigger: AutomationTrigger;
  action: AutomationAction;
  enabled: boolean;
  // Background mode: run silently. The run still executes and records its
  // result + activity, but no summary/answer is pushed to the user's channel
  // (no Telegram ping every time it fires). Toggle via `/automate background
  // <id> on|off` or by asking the agent.
  background?: boolean;
  createdAt: number;
  lastFiredAt?: number;
  fireCount: number;
  lastRunId?: string;
  status: AutomationStatus;
};

export type AutomationRunStatus = "running" | "ok" | "error";

export type AutomationRunThought = {
  ts: number;
  kind: "info" | "step" | "error" | "result";
  text: string;
};

export type AutomationRun = {
  id: string;
  automationId: string;
  tenantId: string;
  ts: number;
  source: string; // which trigger fired it: schedule|composio|webhook|chat|manual
  event: unknown; // the triggering payload (trimmed)
  // Structured digest of the FULL event, computed before trimming, so the job
  // prompt can present a clean unique id + key fields even when `event` was
  // truncated to a lossy `{truncated, preview}` blob.
  eventSummary?: { id: string; fields: string };
  status: AutomationRunStatus;
  jobId?: string; // linked deep-job (mode:"job")
  resultText?: string;
  error?: string;
  thoughts: AutomationRunThought[];
  finishedAt?: number;
};

// --- keys ---------------------------------------------------------------

const ruleKey = (id: string) => `auto:rule:${id}`;
const byTenantKey = (t: string) => `auto:by_tenant:${t}`;
const byTriggerKey = (triggerType: string) => `auto:by_trigger:${triggerType}`;
const SCHEDULE_KEY = "auto:schedule";
const runKey = (id: string) => `auto:run:${id}`;
const runsByRuleKey = (id: string) => `auto:runs:by_rule:${id}`;
const runsByTenantKey = (t: string) => `auto:runs:by_tenant:${t}`;

function newAutomationId(): string {
  return "a_" + globalThis.crypto.randomUUID().replace(/-/g, "").slice(0, 12);
}
function newRunId(): string {
  return "ar_" + globalThis.crypto.randomUUID().replace(/-/g, "").slice(0, 12);
}

// --- rule CRUD ----------------------------------------------------------

export async function putAutomation(
  a: Omit<Automation, "id" | "createdAt" | "fireCount" | "status"> & {
    id?: string;
    createdAt?: number;
    fireCount?: number;
    status?: AutomationStatus;
  }
): Promise<Automation> {
  const store = getStore();
  const full: Automation = {
    id: a.id ?? newAutomationId(),
    tenantId: a.tenantId,
    channel: a.channel,
    sessionId: a.sessionId,
    name: a.name,
    spec: a.spec,
    trigger: a.trigger,
    action: a.action,
    enabled: a.enabled,
    background: a.background,
    createdAt: a.createdAt ?? Date.now(),
    lastFiredAt: a.lastFiredAt,
    fireCount: a.fireCount ?? 0,
    lastRunId: a.lastRunId,
    status: a.status ?? "active",
  };
  await store.set(ruleKey(full.id), full);
  await store.sadd(byTenantKey(full.tenantId), full.id);
  await syncTriggerIndexes(full);
  return full;
}

export async function getAutomation(id: string): Promise<Automation | null> {
  return getStore().get<Automation>(ruleKey(id));
}

export async function listByTenant(tenantId: string): Promise<Automation[]> {
  const store = getStore();
  const ids = await store.smembers(byTenantKey(tenantId));
  const out: Automation[] = [];
  for (const id of ids) {
    const a = await getAutomation(id);
    if (a) out.push(a);
  }
  out.sort((x, y) => y.createdAt - x.createdAt);
  return out;
}

export async function deleteAutomation(id: string): Promise<boolean> {
  const store = getStore();
  const a = await getAutomation(id);
  if (!a) return false;
  await store.srem(byTenantKey(a.tenantId), id);
  if (a.trigger.kind === "composio") {
    await store.srem(byTriggerKey(a.trigger.triggerType), id);
  }
  await store.zrem(SCHEDULE_KEY, id);
  await store.del(ruleKey(id));
  return true;
}

// Keep the trigger-side indexes (composio set, schedule ZSET) consistent
// with the rule's current trigger + enabled state.
async function syncTriggerIndexes(a: Automation): Promise<void> {
  const store = getStore();
  if (a.trigger.kind === "composio") {
    if (a.enabled) await store.sadd(byTriggerKey(a.trigger.triggerType), a.id);
    else await store.srem(byTriggerKey(a.trigger.triggerType), a.id);
  }
  if (a.trigger.kind === "schedule") {
    if (a.enabled) await store.zadd(SCHEDULE_KEY, a.trigger.nextAt, a.id);
    else await store.zrem(SCHEDULE_KEY, a.id);
  }
}

export async function setEnabled(
  id: string,
  enabled: boolean
): Promise<Automation | null> {
  const a = await getAutomation(id);
  if (!a) return null;
  a.enabled = enabled;
  a.status = enabled ? "active" : "paused";
  if (enabled && a.trigger.kind === "schedule") {
    // Re-arm from now so a long-paused schedule doesn't fire a backlog.
    a.trigger.nextAt = nextScheduleAt(a.trigger, Date.now());
  }
  await getStore().set(ruleKey(id), a);
  await syncTriggerIndexes(a);
  return a;
}

// Toggle background (silent) delivery. See Automation.background.
export async function setBackground(
  id: string,
  background: boolean
): Promise<Automation | null> {
  const a = await getAutomation(id);
  if (!a) return null;
  a.background = background;
  await getStore().set(ruleKey(id), a);
  return a;
}

// --- composio matching --------------------------------------------------

export async function matchComposio(
  triggerType: string,
  tenantId: string
): Promise<Automation[]> {
  const store = getStore();
  const ids = await store.smembers(byTriggerKey(triggerType));
  const out: Automation[] = [];
  for (const id of ids) {
    const a = await getAutomation(id);
    if (a && a.enabled && a.tenantId === tenantId) out.push(a);
  }
  return out;
}

// Substring filter: every key/value in filter must appear (case-insensitive)
// somewhere in the JSON-stringified event payload. Cheap + good enough for
// "from this address" / "subject contains" style rules.
export function eventMatchesFilter(
  event: unknown,
  filter?: Record<string, string>
): boolean {
  if (!filter || Object.keys(filter).length === 0) return true;
  const hay = JSON.stringify(event ?? "").toLowerCase();
  return Object.values(filter).every((v) =>
    hay.includes(String(v).toLowerCase())
  );
}

// Guard against feedback loops: GMAIL_NEW_GMAIL_MESSAGE fires for the user's
// OWN drafts and sent mail too (label_ids includes DRAFT / SENT). An agent
// that drafts/sends a reply would otherwise re-trigger itself on its own
// output. Skip those so a "draft a reply" automation only fires on inbound
// mail it didn't create. Other trigger types pass through untouched.
export function isSelfGeneratedComposioEvent(
  triggerType: string,
  event: unknown,
): boolean {
  if (!triggerType.toUpperCase().startsWith("GMAIL_")) return false;
  const labels = (event as { label_ids?: unknown; labelIds?: unknown } | null);
  const raw = labels?.label_ids ?? labels?.labelIds;
  if (!Array.isArray(raw)) return false;
  return raw.some((l) => {
    const s = String(l).toUpperCase();
    return s === "DRAFT" || s === "SENT";
  });
}

// Deterministic "is this email worth spending an LLM on?" pre-gate. Gmail
// auto-categorizes inbound mail with system labels (CATEGORY_PROMOTIONS,
// CATEGORY_SOCIAL, …) plus SPAM. Newsletters, marketing, and social
// notifications make up the bulk of most inboxes and almost never warrant an
// agent turn — so for a "summarize/reply to my email" automation we skip them
// at the runtime BEFORE firing any model call. Real personal/work mail
// (CATEGORY_PERSONAL or no category) passes through untouched.
//
// This is the "runtime decides, not a prompt by default" lever: zero tokens
// spent deciding an email is junk.
//
// Config:
//   GMAIL_AUTOMATION_INCLUDE_BULK=1   disable skipping entirely (fire on all)
//   GMAIL_SKIP_CATEGORIES=promotions,social,forums,spam   override the skip set
const DEFAULT_GMAIL_SKIP = ["promotions", "social", "forums", "spam"];
export function isLowPriorityGmailEvent(
  triggerType: string,
  event: unknown,
): boolean {
  if (!triggerType.toUpperCase().startsWith("GMAIL_")) return false;
  if ((env("GMAIL_AUTOMATION_INCLUDE_BULK") ?? "") === "1") return false;
  const labels = event as { label_ids?: unknown; labelIds?: unknown } | null;
  const raw = labels?.label_ids ?? labels?.labelIds;
  if (!Array.isArray(raw)) return false;
  const skip = (env("GMAIL_SKIP_CATEGORIES") ?? DEFAULT_GMAIL_SKIP.join(","))
    .split(",")
    .map((s) => s.trim().toUpperCase())
    .filter(Boolean);
  // Build the set of Gmail label tokens we treat as skippable, e.g. "promotions"
  // → both "CATEGORY_PROMOTIONS" and "PROMOTIONS"; "spam" → "SPAM".
  const skipLabels = new Set<string>();
  for (const s of skip) {
    skipLabels.add(s);
    skipLabels.add(`CATEGORY_${s}`);
  }
  return raw.some((l) => skipLabels.has(String(l).toUpperCase()));
}

// --- schedule helpers ---------------------------------------------------

export async function dueScheduleIds(
  nowMs: number,
  limit = 25
): Promise<string[]> {
  return getStore().zrangebyscore(SCHEDULE_KEY, 0, nowMs, { limit });
}

// Recompute + persist the next fire time after a scheduled automation runs.
// One-shot schedules (no cron/everyMs) are removed from the ZSET.
export async function rescheduleAutomation(a: Automation): Promise<void> {
  const store = getStore();
  if (a.trigger.kind !== "schedule") return;
  const t = a.trigger;
  if (!t.cron && !t.everyMs) {
    await store.zrem(SCHEDULE_KEY, a.id);
    return;
  }
  t.nextAt = nextScheduleAt(t, Date.now());
  await store.set(ruleKey(a.id), a);
  await store.zadd(SCHEDULE_KEY, t.nextAt, a.id);
}

// Next fire time (epoch ms) strictly after `from`. Supports a fixed interval
// (everyMs) or a standard 5-field cron string ("min hour dom month dow"),
// evaluated against wall-clock time in the trigger's tz (default UTC).
export function nextScheduleAt(
  t: Extract<AutomationTrigger, { kind: "schedule" }>,
  from: number
): number {
  if (t.everyMs && t.everyMs > 0) {
    return from + t.everyMs;
  }
  if (t.cron) {
    const next = nextCronTime(t.cron, from, t.tz);
    if (next) return next;
  }
  // Fallback: an hour out, so a malformed schedule never busy-loops.
  return from + 3_600_000;
}

type CronFields = {
  minute: Set<number>;
  hour: Set<number>;
  dom: Set<number>;
  month: Set<number>;
  dow: Set<number>;
  domStar: boolean;
  dowStar: boolean;
};

function parseCronField(field: string, min: number, max: number): Set<number> {
  const out = new Set<number>();
  for (const part of field.split(",")) {
    let step = 1;
    let range = part;
    const slash = part.indexOf("/");
    if (slash >= 0) {
      step = Math.max(1, parseInt(part.slice(slash + 1), 10) || 1);
      range = part.slice(0, slash);
    }
    let lo = min;
    let hi = max;
    if (range !== "*") {
      const dash = range.indexOf("-");
      if (dash >= 0) {
        lo = parseInt(range.slice(0, dash), 10);
        hi = parseInt(range.slice(dash + 1), 10);
      } else {
        lo = hi = parseInt(range, 10);
      }
    }
    if (Number.isNaN(lo) || Number.isNaN(hi)) continue;
    for (let v = lo; v <= hi; v += step) {
      if (v >= min && v <= max) out.add(v);
    }
  }
  return out;
}

function parseCron(cron: string): CronFields | null {
  const f = cron.trim().split(/\s+/);
  if (f.length !== 5) return null;
  // Normalize dow: accept 0 or 7 for Sunday.
  const dow = parseCronField(f[4].replace(/7/g, "0"), 0, 6);
  return {
    minute: parseCronField(f[0], 0, 59),
    hour: parseCronField(f[1], 0, 23),
    dom: parseCronField(f[2], 1, 31),
    month: parseCronField(f[3], 1, 12),
    dow,
    domStar: f[2].trim() === "*",
    dowStar: f[4].trim() === "*",
  };
}

// Wall-clock fields of an instant in a given IANA tz (default UTC).
function wallClock(
  ms: number,
  tz?: string
): { minute: number; hour: number; dom: number; month: number; dow: number } {
  if (!tz) {
    const d = new Date(ms);
    return {
      minute: d.getUTCMinutes(),
      hour: d.getUTCHours(),
      dom: d.getUTCDate(),
      month: d.getUTCMonth() + 1,
      dow: d.getUTCDay(),
    };
  }
  const fmt = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    hour12: false,
    weekday: "short",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
  });
  const parts = Object.fromEntries(
    fmt.formatToParts(new Date(ms)).map((p) => [p.type, p.value])
  );
  const dowMap: Record<string, number> = {
    Sun: 0,
    Mon: 1,
    Tue: 2,
    Wed: 3,
    Thu: 4,
    Fri: 5,
    Sat: 6,
  };
  return {
    minute: parseInt(parts.minute, 10),
    hour: parseInt(parts.hour === "24" ? "0" : parts.hour, 10),
    dom: parseInt(parts.day, 10),
    month: parseInt(parts.month, 10),
    dow: dowMap[parts.weekday] ?? 0,
  };
}

// Minute-steps forward (bounded to ~366 days) to find the next matching
// instant. Runs only on (re)schedule, so the cost is negligible and the loop
// returns within a day/week for typical daily/weekly crons.
function nextCronTime(cron: string, from: number, tz?: string): number | null {
  const c = parseCron(cron);
  if (!c) return null;
  const MIN = 60_000;
  // Start at the next whole minute strictly after `from`.
  let t = Math.floor(from / MIN) * MIN + MIN;
  const limit = t + 366 * 24 * 60 * MIN;
  for (; t <= limit; t += MIN) {
    const w = wallClock(t, tz);
    if (!c.minute.has(w.minute)) continue;
    if (!c.hour.has(w.hour)) continue;
    if (!c.month.has(w.month)) continue;
    // Cron dom/dow semantics: if both restricted, match either; if one is "*"
    // it doesn't constrain.
    const domOk = c.domStar || c.dom.has(w.dom);
    const dowOk = c.dowStar || c.dow.has(w.dow);
    const dayOk =
      c.domStar || c.dowStar ? domOk && dowOk : domOk || dowOk;
    if (!dayOk) continue;
    return t;
  }
  return null;
}

// --- runs ---------------------------------------------------------------

export async function putRun(
  r: Omit<AutomationRun, "id" | "ts" | "thoughts" | "status"> & {
    id?: string;
    ts?: number;
    thoughts?: AutomationRunThought[];
    status?: AutomationRunStatus;
  }
): Promise<AutomationRun> {
  const store = getStore();
  const full: AutomationRun = {
    id: r.id ?? newRunId(),
    automationId: r.automationId,
    tenantId: r.tenantId,
    ts: r.ts ?? Date.now(),
    source: r.source,
    event: r.event,
    eventSummary: r.eventSummary,
    status: r.status ?? "running",
    jobId: r.jobId,
    resultText: r.resultText,
    error: r.error,
    thoughts: r.thoughts ?? [],
    finishedAt: r.finishedAt,
  };
  await store.set(runKey(full.id), full);
  const score = -full.ts; // newest first via ascending zrangebyscore
  await store.zadd(runsByRuleKey(full.automationId), score, full.id);
  await store.zadd(runsByTenantKey(full.tenantId), score, full.id);
  return full;
}

export async function getRun(id: string): Promise<AutomationRun | null> {
  return getStore().get<AutomationRun>(runKey(id));
}

export async function patchRun(
  id: string,
  patch: Partial<AutomationRun>
): Promise<AutomationRun | null> {
  const cur = await getRun(id);
  if (!cur) return null;
  const next = { ...cur, ...patch };
  await getStore().set(runKey(id), next);
  return next;
}

export async function appendRunThought(
  id: string,
  thought: Omit<AutomationRunThought, "ts"> & { ts?: number }
): Promise<void> {
  const cur = await getRun(id);
  if (!cur) return;
  cur.thoughts.push({ ts: thought.ts ?? Date.now(), kind: thought.kind, text: thought.text });
  if (cur.thoughts.length > 200) cur.thoughts = cur.thoughts.slice(-200);
  await getStore().set(runKey(id), cur);
}

export async function listRunsByRule(
  automationId: string,
  limit = 50
): Promise<AutomationRun[]> {
  return loadRuns(runsByRuleKey(automationId), limit);
}

export async function listRunsByTenant(
  tenantId: string,
  limit = 50
): Promise<AutomationRun[]> {
  return loadRuns(runsByTenantKey(tenantId), limit);
}

async function loadRuns(indexKey: string, limit: number): Promise<AutomationRun[]> {
  const store = getStore();
  const ids = await store.zrangebyscore(indexKey, Number.NEGATIVE_INFINITY, 0, {
    limit,
  });
  const out: AutomationRun[] = [];
  for (const id of ids) {
    const r = await getRun(id);
    if (r) out.push(r);
  }
  return out;
}

// --- firing -------------------------------------------------------------

// Single entrypoint every trigger source funnels through: records a run,
// bumps fire stats, and launches the durable automationWorkflow. Returns the
// runId (or null if the automation is missing/disabled).
export async function fireAutomation(
  automationId: string,
  source: AutomationRun["source"],
  event: unknown
): Promise<string | null> {
  const a = await getAutomation(automationId);
  if (!a || !a.enabled) return null;

  // Account-wide kill switch: when the tenant is paused, nothing fires —
  // automations and workforces alike (workforces run as automation rules).
  const { isTenantPaused } = await import("@/app/lib/tenantPause");
  if (await isTenantPaused(a.tenantId)) return null;

  const run = await putRun({
    automationId: a.id,
    tenantId: a.tenantId,
    source,
    event: trimEvent(event),
    eventSummary: summarizeEvent(event),
    status: "running",
  });

  a.fireCount += 1;
  a.lastFiredAt = run.ts;
  a.lastRunId = run.id;
  await getStore().set(ruleKey(a.id), a);

  // Dynamic import breaks the cycle automations <- automationWorkflow.
  const { start } = await import("workflow/api");
  const { automationWorkflow } = await import("@/app/workflows/automationWorkflow");
  await start(automationWorkflow, [run.id]);
  return run.id;
}

// Extract the identity + display fields from a trigger event so the job prompt
// can lead with a clean unique id instead of a wall of raw payload. Computed on
// the FULL event (before trimEvent), since a truncated Gmail blob hides the
// real message_id inside an escaped, arbitrarily-cut string — which is what
// made the agent grab an id off the spreadsheet and wrongly skip new emails.
// Works across shapes (Gmail/Slack/generic) by probing the payload and any
// nested data/payload object for common field names.
export function summarizeEvent(event: unknown): { id: string; fields: string } {
  const asRec = (v: unknown): Record<string, unknown> | null =>
    v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
  const top = asRec(event);
  if (!top) return { id: "", fields: "" };
  const inner = asRec(top.payload) ?? asRec(top.data) ?? null;
  const pick = (key: string): unknown =>
    top[key] !== undefined ? top[key] : inner ? inner[key] : undefined;
  const firstStr = (...keys: string[]): string => {
    for (const k of keys) {
      const v = pick(k);
      if (v != null && typeof v !== "object" && String(v)) return String(v);
    }
    return "";
  };

  const id = firstStr("message_id", "messageId", "id", "thread_id", "threadId", "log_id");

  const fieldsObj: Record<string, unknown> = {};
  const add = (label: string, ...keys: string[]) => {
    const v = firstStr(...keys);
    if (v) fieldsObj[label] = v.slice(0, 500);
  };
  add("id", "message_id", "messageId", "id");
  add("threadId", "thread_id", "threadId");
  add("from", "from", "sender", "sender_email", "fromEmail");
  add("to", "to", "recipient", "to_email");
  add("subject", "subject", "title");
  add("snippet", "snippet", "preview", "message_text", "text", "body_preview");
  add("timestamp", "message_timestamp", "timestamp", "date", "received_at", "ts");

  const fields = Object.keys(fieldsObj).length ? JSON.stringify(fieldsObj, null, 2) : "";
  return { id, fields };
}

function trimEvent(event: unknown): unknown {
  try {
    const s = JSON.stringify(event);
    if (s.length <= 4000) return event;
    return { truncated: true, preview: s.slice(0, 4000) };
  } catch {
    return String(event).slice(0, 4000);
  }
}
