FROM node:lts AS builder

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ARG APP_BASE_URL
ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_WEBHOOK_SECRET
ARG WHATSAPP_ACCESS_TOKEN
ARG WHATSAPP_PHONE_NUMBER_ID
ARG WHATSAPP_VERIFY_TOKEN
ARG QSTASH_URL
ARG QSTASH_TOKEN
ARG QSTASH_NEXT_SIGNING_KEY
ARG QSTASH_CURRENT_SIGNING_KEY
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG COMPOSIO_API_KEY
ARG COMPOSIO_CALLBACK_URL
ARG FAST_MODEL_NAME
ARG SMART_MODEL_NAME
ARG MODEL_TEMPERATURE
ARG TELEGRAM_ALLOWED_USERS
ARG WHATSAPP_ALLOWED_NUMBERS
ARG SMS_ALLOWED_NUMBERS
ARG TELEGRAM_STREAMING
ARG TELEGRAM_STREAM_EDIT_THROTTLE_MS
ARG TELEGRAM_TYPING_INTERVAL_MS
ARG TELEGRAM_STREAM_CHUNK_CHARS
ARG SSH_HOST
ARG SSH_USER
ARG SSH_PRIVATE_KEY_B64

ENV APP_BASE_URL=$APP_BASE_URL
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
ENV TELEGRAM_WEBHOOK_SECRET=$TELEGRAM_WEBHOOK_SECRET
ENV WHATSAPP_ACCESS_TOKEN=$WHATSAPP_ACCESS_TOKEN
ENV WHATSAPP_PHONE_NUMBER_ID=$WHATSAPP_PHONE_NUMBER_ID
ENV WHATSAPP_VERIFY_TOKEN=$WHATSAPP_VERIFY_TOKEN
ENV QSTASH_URL=$QSTASH_URL
ENV QSTASH_TOKEN=$QSTASH_TOKEN
ENV QSTASH_NEXT_SIGNING_KEY=$QSTASH_NEXT_SIGNING_KEY
ENV QSTASH_CURRENT_SIGNING_KEY=$QSTASH_CURRENT_SIGNING_KEY
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV COMPOSIO_API_KEY=$COMPOSIO_API_KEY
ENV COMPOSIO_CALLBACK_URL=$COMPOSIO_CALLBACK_URL
ENV FAST_MODEL_NAME=$FAST_MODEL_NAME
ENV SMART_MODEL_NAME=$SMART_MODEL_NAME
ENV MODEL_TEMPERATURE=$MODEL_TEMPERATURE
ENV TELEGRAM_ALLOWED_USERS=$TELEGRAM_ALLOWED_USERS
ENV WHATSAPP_ALLOWED_NUMBERS=$WHATSAPP_ALLOWED_NUMBERS
ENV SMS_ALLOWED_NUMBERS=$SMS_ALLOWED_NUMBERS
ENV TELEGRAM_STREAMING=$TELEGRAM_STREAMING
ENV TELEGRAM_STREAM_EDIT_THROTTLE_MS=$TELEGRAM_STREAM_EDIT_THROTTLE_MS
ENV TELEGRAM_TYPING_INTERVAL_MS=$TELEGRAM_TYPING_INTERVAL_MS
ENV TELEGRAM_STREAM_CHUNK_CHARS=$TELEGRAM_STREAM_CHUNK_CHARS
ENV SSH_HOST=$SSH_HOST
ENV SSH_USER=$SSH_USER
ENV SSH_PRIVATE_KEY_B64=$SSH_PRIVATE_KEY_B64

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:lts

WORKDIR /app

ARG APP_BASE_URL
ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_WEBHOOK_SECRET
ARG WHATSAPP_ACCESS_TOKEN
ARG WHATSAPP_PHONE_NUMBER_ID
ARG WHATSAPP_VERIFY_TOKEN
ARG QSTASH_URL
ARG QSTASH_TOKEN
ARG QSTASH_NEXT_SIGNING_KEY
ARG QSTASH_CURRENT_SIGNING_KEY
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG COMPOSIO_API_KEY
ARG COMPOSIO_CALLBACK_URL
ARG FAST_MODEL_NAME
ARG SMART_MODEL_NAME
ARG MODEL_TEMPERATURE
ARG TELEGRAM_ALLOWED_USERS
ARG WHATSAPP_ALLOWED_NUMBERS
ARG SMS_ALLOWED_NUMBERS
ARG TELEGRAM_STREAMING
ARG TELEGRAM_STREAM_EDIT_THROTTLE_MS
ARG TELEGRAM_TYPING_INTERVAL_MS
ARG TELEGRAM_STREAM_CHUNK_CHARS
ARG SSH_HOST
ARG SSH_USER
ARG SSH_PRIVATE_KEY_B64

ENV APP_BASE_URL=$APP_BASE_URL
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
ENV TELEGRAM_WEBHOOK_SECRET=$TELEGRAM_WEBHOOK_SECRET
ENV WHATSAPP_ACCESS_TOKEN=$WHATSAPP_ACCESS_TOKEN
ENV WHATSAPP_PHONE_NUMBER_ID=$WHATSAPP_PHONE_NUMBER_ID
ENV WHATSAPP_VERIFY_TOKEN=$WHATSAPP_VERIFY_TOKEN
ENV QSTASH_URL=$QSTASH_URL
ENV QSTASH_TOKEN=$QSTASH_TOKEN
ENV QSTASH_NEXT_SIGNING_KEY=$QSTASH_NEXT_SIGNING_KEY
ENV QSTASH_CURRENT_SIGNING_KEY=$QSTASH_CURRENT_SIGNING_KEY
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV COMPOSIO_API_KEY=$COMPOSIO_API_KEY
ENV COMPOSIO_CALLBACK_URL=$COMPOSIO_CALLBACK_URL
ENV FAST_MODEL_NAME=$FAST_MODEL_NAME
ENV SMART_MODEL_NAME=$SMART_MODEL_NAME
ENV MODEL_TEMPERATURE=$MODEL_TEMPERATURE
ENV TELEGRAM_ALLOWED_USERS=$TELEGRAM_ALLOWED_USERS
ENV WHATSAPP_ALLOWED_NUMBERS=$WHATSAPP_ALLOWED_NUMBERS
ENV SMS_ALLOWED_NUMBERS=$SMS_ALLOWED_NUMBERS
ENV TELEGRAM_STREAMING=$TELEGRAM_STREAMING
ENV TELEGRAM_STREAM_EDIT_THROTTLE_MS=$TELEGRAM_STREAM_EDIT_THROTTLE_MS
ENV TELEGRAM_TYPING_INTERVAL_MS=$TELEGRAM_TYPING_INTERVAL_MS
ENV TELEGRAM_STREAM_CHUNK_CHARS=$TELEGRAM_STREAM_CHUNK_CHARS
ENV SSH_HOST=$SSH_HOST
ENV SSH_USER=$SSH_USER
ENV SSH_PRIVATE_KEY_B64=$SSH_PRIVATE_KEY_B64

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "start"]
