#ifndef HOLOIROH_IOS_BRIDGE_H
#define HOLOIROH_IOS_BRIDGE_H

#pragma once

/* Generated by cbindgen from holoiroh/ios-bridge/src/lib.rs -- do not edit by hand; regenerate with `cargo run -p holoiroh-ios-bridge --example generate_header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct HoloirohBridge HoloirohBridge;
typedef struct HoloirohSubscription HoloirohSubscription;


/**
 * Pixel-format tag for [`HoloirohFrame::pixel_format`]: tightly-packed 8-bit
 * RGBA (R,G,B,A byte order), `width * 4` bytes per row. Historical: no
 * longer emitted by this build -- see [`HOLOIROH_PIXFMT_BGRA8`].
 */
#define HOLOIROH_PIXFMT_RGBA8 0

/**
 * Pixel-format tag for [`HoloirohFrame::pixel_format`]: tightly-packed 8-bit
 * BGRA (B,G,R,A byte order) -- what [`holoiroh_ios_bridge_poll_next_frame`]
 * actually emits. Maps to Swift's `kCVPixelFormatType_32BGRA`.
 *
 * Why BGRA, not RGBA: `kCVPixelFormatType_32RGBA` is NOT a supported
 * CoreVideo pool/IOSurface format on iOS (it is on macOS), so the Swift
 * side's `CVPixelBufferPoolCreate` silently returned nil and dropped EVERY
 * frame -- live-witnessed as a permanent black screen while the on-device
 * decode pipeline was verifiably delivering 20-40fps the whole session
 * (device console: `vdec stats fps=20..40`, zero errors anywhere). 32BGRA
 * is the universally-supported iOS display format, so the bridge swizzles
 * R<->B during copy-out and tags frames with this constant.
 */
#define HOLOIROH_PIXFMT_BGRA8 1

/**
 * Result/error-code convention shared by every fallible function in this
 * module: `0` = success, negative = failure. The sign convention is fixed:
 * callers distinguish success from failure by the sign of the return value.
 */
typedef int HoloirohStatus;

/**
 * One decoded media frame's metadata handed back across the FFI boundary by
 * [`holoiroh_ios_bridge_poll_next_frame`]. The frame *bytes* are written into
 * a caller-allocated buffer (see module doc, "Frames are
 * caller-allocated-and-filled"); this struct carries the metadata the Swift
 * side needs to hand those bytes to `CVPixelBuffer` /
 * `AVSampleBufferDisplayLayer` correctly.
 */
typedef struct {
  uint32_t width;
  uint32_t height;
  /**
   * Presentation timestamp, microseconds since the subscription started
   * (the decoded frame's own `timestamp`, which is `Duration::ZERO` before
   * the pipeline assigns a PTS).
   */
  uint64_t timestamp_us;
  /**
   * Pixel format of the bytes written into the caller's buffer. Always
   * [`HOLOIROH_PIXFMT_RGBA8`] in this build: the frame is normalized to
   * tightly-packed 8-bit RGBA via `VideoFrame::rgba_image()`, so
   * `bytes_per_row == width * 4` and total length `== width * height * 4`.
   * Kept as a field (rather than assumed) so the Swift side can pick the
   * matching `kCVPixelFormatType_*` without guessing, and so a future
   * zero-copy path can report a different format without an ABI change.
   */
  uint32_t pixel_format;
  /**
   * 0 = video, 1 = audio. Kept as a plain tag rather than a Rust `enum`
   * crossing FFI, since `#[repr(C)]` enums are still awkward to bind safely
   * from Swift compared to a plain integer + doc comment. Always `0`
   * (video) in this build -- audio is not yet pulled across this bridge.
   */
  uint8_t kind;
} HoloirohFrame;

#define HOLOIROH_OK 0

#define HOLOIROH_ERR_UNKNOWN -1

#define HOLOIROH_ERR_INVALID_TICKET -2

#define HOLOIROH_ERR_CONNECT_FAILED -3

#define HOLOIROH_ERR_NOT_CONNECTED -4

#define HOLOIROH_ERR_BUFFER_TOO_SMALL -5

/**
 * The subscription's video track has ended (producer dropped): no further
 * frames will ever arrive. Distinct from "no frame yet" (`0`).
 */
#define HOLOIROH_ERR_ENDED -6

/**
 * The requested operation is not supported by this build. No function
 * currently returns this (the control-channel functions, which used to,
 * are implemented as of this build) -- the constant is kept so the C ABI's
 * error-code numbering stays stable.
 */
#define HOLOIROH_ERR_UNSUPPORTED -7

/**
 * A required pointer argument was null.
 */
#define HOLOIROH_ERR_NULL_ARG -8

/**
 * A Rust panic was caught at the FFI boundary (should never happen; the
 * boundary catches it and returns this rather than unwinding into C, which
 * would be undefined behavior).
 */
#define HOLOIROH_ERR_PANIC -9

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a bridge with a generated, process-lifetime iroh identity.
 *
 * This constructor remains available for ABI compatibility. Persistent clients
 * must use [`holoiroh_ios_bridge_new_with_secret_key`].
 *
 * # Safety
 * The returned pointer, if non-null, must be released exactly once with
 * [`holoiroh_ios_bridge_free`].
 */
HoloirohBridge *holoiroh_ios_bridge_new(void);

/**
 * Creates a bridge whose endpoint identity is derived from one 32-byte secret
 * key seed. Returns null unless `key_ptr` is non-null and `key_len` is exactly
 * 32, or if runtime or endpoint construction fails.
 *
 * # Safety
 * `key_ptr` must be readable for exactly `key_len` bytes. The returned pointer,
 * if non-null, must be released exactly once with
 * [`holoiroh_ios_bridge_free`].
 */
HoloirohBridge *holoiroh_ios_bridge_new_with_secret_key(const uint8_t *key_ptr, uintptr_t key_len);

/**
 * Releases a bridge instance created by [`holoiroh_ios_bridge_new`], tearing
 * down any active subscription, its `iroh_live::Live` session (via
 * `live.shutdown().await`), and its Tokio runtime. Passing null is a no-op
 * (matches `free(NULL)` C convention).
 *
 * # Safety
 * `bridge` must either be null or a pointer previously returned by
 * [`holoiroh_ios_bridge_new`] and not already freed. The caller must not use
 * `bridge` again after this call. Any [`HoloirohSubscription`] obtained from
 * this bridge must be freed *before* this call (the subscription's video
 * track is driven by the bridge's runtime).
 */
void holoiroh_ios_bridge_free(HoloirohBridge *bridge);

/**
 * Probes daemon reachability with a temporary generated endpoint identity.
 *
 * This function remains available for ABI compatibility. Persistent clients
 * must use [`holoiroh_ios_bridge_probe_reachable_with_secret_key`].
 *
 * # Safety
 * `ticket_cstr` must be a valid null-terminated C string, or null.
 */
bool holoiroh_ios_bridge_probe_reachable(const char *ticket_cstr, uint64_t timeout_ms);

/**
 * Probes daemon reachability from an endpoint derived from one 32-byte secret
 * key seed. Returns false unless the ticket is valid, `key_ptr` is non-null,
 * and `key_len` is exactly 32. The temporary endpoint is explicitly closed
 * before this function returns.
 *
 * # Safety
 * `ticket_cstr` must be a valid null-terminated C string, or null. `key_ptr`
 * must be readable for exactly `key_len` bytes.
 */
bool holoiroh_ios_bridge_probe_reachable_with_secret_key(const char *ticket_cstr,
                                                         uint64_t timeout_ms,
                                                         const uint8_t *key_ptr,
                                                         uintptr_t key_len);

/**
 * Parses an `iroh-live:` ticket string (the format
 * [`LiveTicket`](iroh_live::ticket::LiveTicket) serializes to -- see
 * `../ios/IROH_FFI.md`'s Finding (b)) and connects the bridge's
 * `iroh_live::Live` session to the peer it describes, subscribing to the
 * named broadcast. Blocks the calling thread until the connection attempt
 * resolves (success or failure) -- call from a background queue, not the main
 * thread.
 *
 * `ticket_cstr` must be a null-terminated UTF-8 C string, e.g. as produced by
 * Swift's `String.withCString`. `out_error` may be null if the caller doesn't
 * want a human-readable error message on failure (the [`HoloirohStatus`]
 * return value alone still distinguishes failure modes).
 *
 * Returns [`HOLOIROH_OK`] on success, or a negative [`HoloirohStatus`] (see
 * constants above) on failure.
 *
 * # Safety
 * `bridge` must be a live pointer from [`holoiroh_ios_bridge_new`].
 * `ticket_cstr` must be a valid null-terminated C string for the duration of
 * this call. If non-null, `out_error` must be a valid, writable
 * `*mut c_char` slot; any string written there must later be freed via
 * [`holoiroh_ios_bridge_free_error_string`].
 */
HoloirohStatus holoiroh_ios_bridge_ticket_connect(HoloirohBridge *bridge,
                                                  const char *ticket_cstr,
                                                  char **out_error);

/**
 * Begins consuming the video track of the broadcast on an already-connected
 * bridge (see [`holoiroh_ios_bridge_ticket_connect`]), returning an opaque
 * subscription handle that [`holoiroh_ios_bridge_poll_next_frame`] reads
 * from. Internally calls `subscription.broadcast().video_ready().await`,
 * which blocks until the publisher's catalog advertises at least one video
 * rendition, then subscribes to the best-quality rendition and starts the
 * decoder pipeline (VideoToolbox on Apple targets).
 *
 * Blocks the calling thread until a video rendition is available -- call from
 * a background queue. Returns null on failure (bridge not connected yet, or
 * the broadcast never advertised a video track); check `out_error` if
 * non-null.
 *
 * # Safety
 * `bridge` must be a live, connected pointer (post successful
 * [`holoiroh_ios_bridge_ticket_connect`]). `out_error` follows the same
 * contract as in [`holoiroh_ios_bridge_ticket_connect`]. The returned
 * pointer, if non-null, must eventually be passed to exactly one call of
 * [`holoiroh_ios_bridge_subscription_free`], and *before* the parent bridge
 * is freed.
 */
HoloirohSubscription *holoiroh_ios_bridge_subscribe(HoloirohBridge *bridge, char **out_error);

/**
 * Releases a subscription created by [`holoiroh_ios_bridge_subscribe`].
 * Passing null is a no-op. Dropping the video track stops the decoder
 * pipeline for that track.
 *
 * # Safety
 * `subscription` must either be null or a pointer previously returned by
 * [`holoiroh_ios_bridge_subscribe`] and not already freed.
 */
void holoiroh_ios_bridge_subscription_free(HoloirohSubscription *subscription);

/**
 * Non-blocking poll for the latest decoded video frame on an active
 * subscription. Fills `out_frame` (metadata) and copies the frame's RGBA8
 * bytes into caller-owned `buf`, returning the number of bytes actually
 * written into `buf` on success.
 *
 * Semantics (all non-negative returns are byte counts; negative returns are
 * [`HoloirohStatus`] errors):
 * - **No frame available yet** -> returns `0`, `out_frame` left untouched.
 *   Not an error; poll again shortly (e.g. on a timer-driven loop on a
 *   background queue). Internally this is `VideoTrack::try_recv()` returning
 *   `None`, which also drains older buffered frames so you always get the
 *   most recent decoded frame (the low-latency "latest frame wins" behavior a
 *   live mirror wants).
 * - **A frame is available and fits** -> copies `width * height * 4` RGBA8
 *   bytes into `buf`, fills `out_frame`, returns that byte count.
 * - **A frame is available but `buf_capacity` is too small** -> returns
 *   [`HOLOIROH_ERR_BUFFER_TOO_SMALL`] and writes the frame's real
 *   `width`/`height`/`pixel_format` into `out_frame` so the caller can size a
 *   `width * height * 4` buffer and poll again. (The frame itself is
 *   consumed; the caller re-polls for the next one -- acceptable for a live
 *   mirror where a single dropped frame is invisible, and the caller should
 *   size its buffer to the largest expected resolution up front to avoid this
 *   path entirely.)
 * - **The track has ended** (publisher dropped it) -> returns
 *   [`HOLOIROH_ERR_ENDED`]; no further frames will arrive.
 *
 * # Safety
 * `subscription` must be a live pointer from
 * [`holoiroh_ios_bridge_subscribe`]. `buf` must be valid and writable for
 * `buf_capacity` bytes (or null iff `buf_capacity` is 0). `out_frame` must be
 * a valid, writable `*mut HoloirohFrame`.
 */
int holoiroh_ios_bridge_poll_next_frame(HoloirohSubscription *subscription,
                                        uint8_t *buf,
                                        uintptr_t buf_capacity,
                                        HoloirohFrame *out_frame);

/**
 * Establishes the control channel to the Mac daemon the bridge is
 * ticket-connected to: dials the peer stored by
 * [`holoiroh_ios_bridge_ticket_connect`] on [`CONTROL_ALPN`], opens one
 * bidirectional QUIC stream, performs the PIN handshake, and waits (up to
 * [`CONTROL_HANDSHAKE_TIMEOUT`]) for the daemon's first reply line.
 *
 * Wire contract (mirror of `mac-daemon/src/control_channel.rs`):
 * - The PIN goes out as a **bare** (non-envelope) NDJSON line
 *   `{"type":"pin","pin":"..."}` -- exactly what the daemon's
 *   `ControlChannel::authenticate` gate requires as the very first line
 *   from an unrecognized device. (The gate would reject an envelope-
 *   wrapped PIN, so this one line is deliberately not enveloped.)
 * - On success the daemon's first line is its envelope-wrapped greeting
 *   (`payload` = `{"type":"status","text":"control channel ready"}`) ->
 *   returns [`HOLOIROH_OK`], stores the send stream on the bridge, and
 *   spawns a reader task queueing every subsequent NDJSON line for
 *   [`holoiroh_ios_bridge_poll_control_event`].
 * - On auth failure the daemon's first (and only) line is a **bare**
 *   `{"type":"auth_rejected","text":...}` -> returns
 *   [`HOLOIROH_ERR_CONNECT_FAILED`] with the daemon's reason in
 *   `*out_error`. Timeout / early close also map to
 *   [`HOLOIROH_ERR_CONNECT_FAILED`].
 *
 * Everything *after* the handshake is signed envelope JSON in both directions
 * (`TaskEnvelope<ClientMessage>` / `TaskEnvelope<ServerMessage>`, see
 * `PROTOCOL.md`). [`holoiroh_ios_bridge_control_send`] accepts an unsigned
 * typed client envelope, validates its session and sequence, signs it with the
 * bridge endpoint identity, and writes the signed line. The reader verifies
 * every daemon envelope against the authenticated transport peer before it
 * queues JSON for [`holoiroh_ios_bridge_poll_control_event`].
 *
 * Idempotent: returns [`HOLOIROH_OK`] immediately if already connected
 * (checked and connected under one lock, so concurrent callers serialize
 * rather than double-dial). Requires a prior successful
 * [`holoiroh_ios_bridge_ticket_connect`] (which stores the peer address)
 * -- returns [`HOLOIROH_ERR_NOT_CONNECTED`] otherwise. Blocks the calling
 * thread; call from a background queue.
 *
 * Note: for a device the daemon has *already allowlisted*, the daemon's
 * auth gate never consumes the PIN line; it instead falls through to the
 * daemon's main envelope loop, which replies with one harmless
 * `{"type":"error","text":"malformed envelope: ..."}` envelope that will
 * surface once via [`holoiroh_ios_bridge_poll_control_event`]. This is
 * cosmetic: the ready greeting is written before that loop reads anything,
 * so it still arrives first and this function still returns
 * [`HOLOIROH_OK`].
 *
 * # Safety
 * `bridge` must be a live pointer from [`holoiroh_ios_bridge_new`].
 * `pin_cstr` must be a valid null-terminated C string for the duration of
 * this call. `out_error` follows the same contract as in
 * [`holoiroh_ios_bridge_ticket_connect`].
 */
HoloirohStatus holoiroh_ios_bridge_control_connect(HoloirohBridge *bridge,
                                                   const char *pin_cstr,
                                                   char **out_error);

/**
 * Accepts one unsigned `TaskEnvelope<ClientMessage>` JSON value from Swift.
 * The bridge rejects caller-supplied signatures and invalid envelope metadata,
 * binds the envelope to the verified session and next outbound sequence, signs
 * it with the bridge endpoint's Ed25519 identity, serializes the signed envelope
 * as one NDJSON line, and writes it to the connected Mac daemon. Blocks until
 * the QUIC stream accepts the bytes; call from a background queue.
 *
 * Returns [`HOLOIROH_ERR_NOT_CONNECTED`] until
 * [`holoiroh_ios_bridge_control_connect`] has succeeded. On a write
 * failure (peer gone, connection lost) returns
 * [`HOLOIROH_ERR_CONNECT_FAILED`] and drops the stored stream so a later
 * `control_connect` call can re-dial.
 *
 * # Safety
 * `bridge` must be a live pointer from [`holoiroh_ios_bridge_new`].
 * `json_cstr` must be a valid null-terminated C string for the duration of
 * this call. `out_error` follows the same contract as elsewhere in this
 * module.
 */
HoloirohStatus holoiroh_ios_bridge_control_send(HoloirohBridge *bridge,
                                                const char *json_cstr,
                                                char **out_error);

/**
 * Non-blocking poll for the next verified `TaskEnvelope<ServerMessage>` NDJSON
 * line received after control authentication. The reader rejects malformed,
 * unsigned, incorrectly signed, expired, replayed, or out-of-sequence daemon
 * envelopes before this function can return them.
 *
 * Semantics:
 * - **A line is queued** -> writes a freshly-allocated null-terminated
 *   copy to `*out_json` (caller frees via
 *   [`holoiroh_ios_bridge_free_error_string`]) and returns [`HOLOIROH_OK`].
 * - **Queue empty, stream alive** -> sets `*out_json` to null and returns
 *   [`HOLOIROH_OK`]; poll again shortly.
 * - **Queue empty, stream ended** (daemon closed it, or a prior
 *   `control_send` failed) -> sets `*out_json` to null and returns
 *   [`HOLOIROH_ERR_ENDED`]; a fresh
 *   [`holoiroh_ios_bridge_control_connect`] may re-establish the channel.
 *
 * # Safety
 * `bridge` must be a live pointer from [`holoiroh_ios_bridge_new`].
 * `out_json` must be a valid writable `*mut *mut c_char`; the string
 * written there (if any) must later be freed via
 * [`holoiroh_ios_bridge_free_error_string`]. `out_error` follows the same
 * contract as elsewhere in this module.
 */
HoloirohStatus holoiroh_ios_bridge_poll_control_event(HoloirohBridge *bridge,
                                                      char **out_json,
                                                      char **out_error);

/**
 * Frees a C string previously allocated by this crate and handed back through
 * an `out_error`/`out_json` out-parameter (e.g. from
 * [`holoiroh_ios_bridge_ticket_connect`]). Passing null is a no-op.
 *
 * Every Rust-allocated string crossing this FFI boundary **must** be freed
 * via this function, never via Swift's own memory management or libc `free`
 * directly -- the allocator that created it (Rust's global allocator, via
 * `CString::into_raw`) must also be the one that deallocates it.
 *
 * # Safety
 * `s` must either be null or a pointer previously returned in an
 * `out_error`/`out_json` parameter by a function in this crate, and must not
 * have been freed already.
 */
void holoiroh_ios_bridge_free_error_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HOLOIROH_IOS_BRIDGE_H */
