#ifndef HOLOIROH_IOS_BRIDGE_H
#define HOLOIROH_IOS_BRIDGE_H

#pragma once

/*
 * C ABI for the holoiroh-ios-bridge Rust staticlib (iroh-live subscribe ->
 * iOS). The type/constant declarations below are generated by cbindgen from
 * holoiroh/ios-bridge/src/lib.rs; the function prototypes are maintained
 * alongside them (cbindgen 0.27 does not yet recognize edition-2024's
 * `#[unsafe(no_mangle)]` attribute form, so it emits the types but skips the
 * `extern "C"` functions -- the prototypes here are hand-kept 1:1 with the Rust
 * signatures and verified against `nm libholoiroh_ios_bridge.a`). Regenerate
 * the type section with:
 *   cbindgen --config cbindgen.toml --crate holoiroh-ios-bridge \
 *     --output include/HoloirohIosBridge.h
 * and re-append the function block below if it is overwritten.
 *
 * This header is the primary Swift-visible surface (there is no uniffi codegen
 * on the iroh-live side -- see ../ios/IROH_FFI.md); it is paired with
 * module.modulemap so Swift can `import HoloirohIosBridge`.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Pixel-format tag for `HoloirohFrame::pixel_format`: tightly-packed 8-bit
 * RGBA (R,G,B,A byte order), `width * 4` bytes per row. Maps to Swift's
 * `kCVPixelFormatType_32RGBA`.
 */
#define HOLOIROH_PIXFMT_RGBA8 0

/**
 * Tightly-packed 8-bit BGRA (B,G,R,A byte order) -- what
 * `holoiroh_ios_bridge_poll_next_frame` actually emits. Maps to Swift's
 * `kCVPixelFormatType_32BGRA`, the universally-supported iOS display
 * format (32RGBA pools are NOT supported by CoreVideo on iOS -- feeding
 * RGBA made every CVPixelBufferPool creation fail silently, dropping all
 * frames: the permanent-black-screen bug).
 */
#define HOLOIROH_PIXFMT_BGRA8 1

/**
 * Result/error-code convention shared by every fallible function in this
 * module: `0` = success, negative = failure. The sign convention is fixed:
 * callers distinguish success from failure by the sign of the return value.
 */
typedef int HoloirohStatus;

/**
 * Opaque handle to a running bridge instance: owns the Tokio runtime, the
 * `iroh_live::Live` session, and (once connected) the current subscription.
 * Obtained via `holoiroh_ios_bridge_new`, released via
 * `holoiroh_ios_bridge_free`.
 *
 * Never constructed on the Rust side as a real value -- only ever handed out
 * as `Box::into_raw(Box::new(BridgeInner {..}))` cast to this opaque type, so
 * C/Swift can hold and pass the pointer around without any ability to read
 * its layout. Distinct named type (not a bare `void*`) so a caller gets a
 * type error if they pass the wrong handle to the wrong function.
 *
 * Deliberately an INCOMPLETE type (forward declaration, no body): a defined
 * struct -- even the zero-sized `uint8_t _private[0]` idiom this previously
 * used -- imports into Swift as a nominal type, making every API take
 * `UnsafeMutablePointer<HoloirohBridge>`, which broke the Swift wrapper's
 * `OpaquePointer` handle fields the first time the module was actually
 * imported (witnessed on the first real device build). An incomplete type
 * imports as Swift `OpaquePointer`, which is exactly the semantics an opaque
 * handle should have on both languages' sides.
 */
typedef struct HoloirohBridge HoloirohBridge;

/**
 * Opaque handle to an active video subscription (post-`subscribe`), distinct
 * from `HoloirohBridge` so a bridge holds zero or one active video
 * subscriptions independently of its connection lifecycle. Obtained via
 * `holoiroh_ios_bridge_subscribe`, released via
 * `holoiroh_ios_bridge_subscription_free`. Incomplete type for the same
 * Swift-`OpaquePointer` import reason as `HoloirohBridge` above.
 */
typedef struct HoloirohSubscription HoloirohSubscription;

/**
 * One decoded media frame's metadata handed back across the FFI boundary by
 * `holoiroh_ios_bridge_poll_next_frame`. The frame *bytes* are written into
 * a caller-allocated buffer (see the Rust module doc, "Frames are
 * caller-allocated-and-filled"); this struct carries the metadata the Swift
 * side needs to hand those bytes to `CVPixelBuffer` /
 * `AVSampleBufferDisplayLayer` correctly.
 */
typedef struct {
  uint32_t width;
  uint32_t height;
  /**
   * Presentation timestamp, microseconds since the subscription started
   * (the decoded frame's own `timestamp`, which is `Duration::ZERO` before
   * the pipeline assigns a PTS).
   */
  uint64_t timestamp_us;
  /**
   * Pixel format of the bytes written into the caller's buffer. Always
   * `HOLOIROH_PIXFMT_RGBA8` in this build: the frame is normalized to
   * tightly-packed 8-bit RGBA via `VideoFrame::rgba_image()`, so
   * `bytes_per_row == width * 4` and total length `== width * height * 4`.
   */
  uint32_t pixel_format;
  /**
   * 0 = video, 1 = audio. Always `0` (video) in this build -- audio is not
   * yet pulled across this bridge.
   */
  uint8_t kind;
} HoloirohFrame;

#define HOLOIROH_OK 0

#define HOLOIROH_ERR_UNKNOWN -1

#define HOLOIROH_ERR_INVALID_TICKET -2

#define HOLOIROH_ERR_CONNECT_FAILED -3

#define HOLOIROH_ERR_NOT_CONNECTED -4

#define HOLOIROH_ERR_BUFFER_TOO_SMALL -5

/**
 * The subscription's video track has ended (producer dropped): no further
 * frames will ever arrive. Distinct from "no frame yet" (`0`).
 */
#define HOLOIROH_ERR_ENDED -6

/**
 * The requested operation is not supported by this build. No function
 * currently returns this (the control-channel functions are implemented as
 * of this build); kept so the error-code numbering stays stable.
 */
#define HOLOIROH_ERR_UNSUPPORTED -7

/**
 * A required pointer argument was null.
 */
#define HOLOIROH_ERR_NULL_ARG -8

/**
 * A Rust panic was caught at the FFI boundary (should never happen; the
 * boundary catches it and returns this rather than unwinding into C).
 */
#define HOLOIROH_ERR_PANIC -9

/* ---------------------------------------------------------------------------
 * Functions (hand-kept 1:1 with the `extern "C"` fns in src/lib.rs; verified
 * against `nm target/aarch64-apple-ios/debug/libholoiroh_ios_bridge.a`).
 * ------------------------------------------------------------------------- */

/**
 * Creates a new bridge (Tokio runtime + iroh Endpoint + iroh-live Live
 * session). Does NOT connect yet. Returns NULL on failure. The returned
 * pointer must eventually be passed to exactly one holoiroh_ios_bridge_free.
 */
HoloirohBridge *holoiroh_ios_bridge_new(void);

/**
 * Frees a bridge created by holoiroh_ios_bridge_new (tears down any
 * subscription, the Live session, and the runtime). NULL is a no-op. Free any
 * HoloirohSubscription from this bridge BEFORE calling this.
 */
void holoiroh_ios_bridge_free(HoloirohBridge *bridge);

/**
 * Parses an `iroh-live:` ticket C string and connects+subscribes the bridge's
 * Live session to the peer it describes. Blocks; call off the main thread.
 * Returns HOLOIROH_OK, or a negative HoloirohStatus. On failure, writes a
 * heap-allocated error string to *out_error (if out_error != NULL), which the
 * caller must free via holoiroh_ios_bridge_free_error_string.
 */
HoloirohStatus holoiroh_ios_bridge_ticket_connect(HoloirohBridge *bridge,
                                                   const char *ticket_cstr,
                                                   char **out_error);

/**
 * Begins consuming the broadcast's video track on a connected bridge (calls
 * broadcast().video_ready() internally). Blocks until a video rendition
 * appears; call off the main thread. Returns an opaque subscription handle, or
 * NULL on failure (with *out_error set if non-NULL). The handle must be freed
 * via holoiroh_ios_bridge_subscription_free before the parent bridge is freed.
 */
HoloirohSubscription *holoiroh_ios_bridge_subscribe(HoloirohBridge *bridge,
                                                    char **out_error);

/**
 * Frees a subscription created by holoiroh_ios_bridge_subscribe. NULL is a
 * no-op.
 */
void holoiroh_ios_bridge_subscription_free(HoloirohSubscription *subscription);

/**
 * Non-blocking poll for the latest decoded video frame. Fills *out_frame
 * (metadata) and copies RGBA8 bytes into caller-owned buf (buf_capacity
 * bytes), returning the byte count written (>= 0). Special returns:
 *   0                              -> no frame yet (poll again shortly)
 *   HOLOIROH_ERR_BUFFER_TOO_SMALL  -> frame too big; out_frame carries the
 *                                     real width/height so the caller can size
 *                                     a width*height*4 buffer and retry
 *   HOLOIROH_ERR_ENDED             -> track ended, no more frames
 *   other negative                 -> error
 * buf may be NULL only if buf_capacity is 0.
 */
int holoiroh_ios_bridge_poll_next_frame(HoloirohSubscription *subscription,
                                        uint8_t *buf,
                                        size_t buf_capacity,
                                        HoloirohFrame *out_frame);

/**
 * Establishes the control channel (holoiroh/control/1 ALPN) to the Mac the
 * bridge is ticket-connected to: dials the peer stored by
 * holoiroh_ios_bridge_ticket_connect, opens one bidirectional stream, sends
 * the bare PIN handshake line {"type":"pin","pin":...}, and waits (up to
 * 30s) for the daemon's first reply line. Returns HOLOIROH_OK once the
 * daemon's "control channel ready" greeting arrives (a reader task then
 * queues every subsequent NDJSON line for
 * holoiroh_ios_bridge_poll_control_event); HOLOIROH_ERR_CONNECT_FAILED on
 * auth_rejected / timeout / transport failure (with *out_error set if
 * non-NULL); HOLOIROH_ERR_NOT_CONNECTED if ticket_connect hasn't succeeded
 * yet. Idempotent: an already-connected bridge returns HOLOIROH_OK
 * immediately. Blocks; call off the main thread.
 */
HoloirohStatus holoiroh_ios_bridge_control_connect(HoloirohBridge *bridge,
                                                   const char *pin_cstr,
                                                   char **out_error);

/**
 * Sends one NDJSON line (a PROTOCOL.md TaskEnvelope<ClientMessage> the
 * caller has already serialized; a trailing \n is appended if missing) over
 * the connected control channel. Returns HOLOIROH_ERR_NOT_CONNECTED until
 * holoiroh_ios_bridge_control_connect has succeeded;
 * HOLOIROH_ERR_CONNECT_FAILED if the stream died (a later control_connect
 * call may re-dial). Blocks until the bytes are accepted by the QUIC
 * stream; call off the main thread.
 */
HoloirohStatus holoiroh_ios_bridge_control_send(HoloirohBridge *bridge,
                                                const char *json_cstr,
                                                char **out_error);

/**
 * Non-blocking poll for the next NDJSON line (a PROTOCOL.md
 * TaskEnvelope<ServerMessage>, or a bare ServerMessage for pre-session
 * replies) received on the control channel:
 *   line available -> *out_json = Rust-allocated C string (free it with
 *                     holoiroh_ios_bridge_free_error_string), returns
 *                     HOLOIROH_OK
 *   queue empty    -> *out_json = NULL, returns HOLOIROH_OK (poll again)
 *   stream ended   -> *out_json = NULL, returns HOLOIROH_ERR_ENDED
 */
HoloirohStatus holoiroh_ios_bridge_poll_control_event(HoloirohBridge *bridge,
                                                      char **out_json,
                                                      char **out_error);

/**
 * Frees a C string previously returned via an out_error/out_json out-param by
 * a function in this crate (Rust allocator). NULL is a no-op. Never free such
 * strings with libc free() -- the Rust allocator must deallocate them.
 */
void holoiroh_ios_bridge_free_error_string(char *s);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* HOLOIROH_IOS_BRIDGE_H */
